### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by Boycce** [jonschlinkert/isobject#15]
Can you please shed some light on the use case of such repositories, apart from being a reference? Just would like to know if i'm missing anything, thanks.

**Comment by nlac** [comment]
My first association was this https://en.wikipedia.org/wiki/Cargo_cult_programming.
Perhaps, instead of creating infinite number of separate node modules for every single 50 byte-long methods, would be better to gather them into one utility library. Especially in the era when the node_modules directories take more space than all the downloaded porn:)

**Comment by jonschlinkert** [comment]
> Can you please shed some light on the use case of such repositories

Yes. 

> would like to know if i'm missing anything, thanks.

Yes.
